### ISSUE TITLE
Implement shortcut for commands

### ISSUE THREAD

**Issue by nubnubyas** [AY2324S1-CS2103T-T14-3/tp#106]
Allow shortcuts for all existing commands, the shortcuts would follow the following format:
Add -> a
Clear -> c
Delete -> d
Edit -> e
Find -> f
List  -> li
Log -> lo
Undo -> u
Help -> h
Exit -> ex

**Comment by WZWren** [comment]
This has been partially implemented with the latest merge into the `master` branch (#111).

**Comment by kanna-1** [comment]
List shortcut is updated to ls.
Shorcuts for log, alog, and clog has also been implemented.
