### ISSUE TITLE
Enhancement of test cases

### ISSUE THREAD

**Issue by kanna-1** [AY2324S1-CS2103T-T14-3/tp#113]
As per the test case heuristics we learnt throughout the course, there is a need to have more robust testing

These are the applicable heuristics:
1. Equivalent Partitions
2. Boundary Value Analysis
3. Combining Multiple Inputs

**Comment by WZWren** [comment]
As we have reached the ending phases of the milestone, is this safe to close? @kanna-1

**Comment by kanna-1** [comment]
Yes.
