### ISSUE TITLE
Update Command Box Information 

### ISSUE THREAD

**Issue by WeeeHung** [AY2324S1-CS2103T-T14-3/tp#128]
This is the current Command Box result when i type `add` as the command

``` 
Invalid command format! 
add or a: Adds a Patient to the patient list. Parameters: n/NAME id/NRIC p/PHONE e/EMAIL a/ADDRESS [ap/APPOINTMENT] [t/TAG]...[m/MEDICAL_HISTORY]...
Example 1: add n/John Doe id/S8765432A p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 ap/2023-10-17 11:00 13:00 m/hypochondriac m/on Medicine XYZ t/owesMoney 
Example 2: a n/Alex Yeohid/S6742632F p/85743822 e/alex@example.com a/420, Country Road, #02-25 ap/2023-11-10 11:00 13:00 m/tachycardia m/on Medicine CHS t/owesMoney
```

Few Issues with this command result (possibly similar for other command help prompts).
1. there is missing space between name and id for example 2
2. the appointment format is wrong for both examples. ie. the new formatting is DD-MM-YYYY
3. example still contains deprecated tag `t/` which might mislead users

**Comment by kanna-1** [comment]
As of our latest repo, this issue has been resolved.
