### ISSUE TITLE
[PE-D][Tester F] Cannot have duplicate name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T14-3/tp#160]
![image.png](https://raw.githubusercontent.com/songfangyl/ped/main/files/7f058c20-ab4a-472e-be7a-7e66540245d1.png)

The app not allowed multiple patient with same name, however I think that is quite a common case to have two people with exact same name.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: songfangyl/ped#5

**Comment by kanna-1** [comment]
Hmm. perhaps name can be duplicated but not Nric then.

**Comment by WZWren** [comment]
This is a duplicate issue (#189).
