### ISSUE TITLE
[PE-D][Tester D] unable to undo completely

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T14-3/tp#163]
![Screenshot 2023-11-03 at 4.33.24 PM.png](https://raw.githubusercontent.com/chewjh1234/ped/main/files/46fd0ef4-b747-4824-9726-4a68d512a53c.png)

unable to undo the first command i entered - addition of john

edit: realise that there is a maximum size for the undo call stack. perhaps you could include '7' in the UG

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: chewjh1234/ped#4

**Comment by kanna-1** [comment]
Not sure what `7` is. The stack size in Java is determined by the limitations in the Java platform.

**Comment by WeeeHung** [comment]
Enquired on the steps to replicate bug. More info on https://github.com/chewjh1234/ped/issues/4#issuecomment-1795057242
