### ISSUE TITLE
[PE-D][Tester A] UI screenshot is not annotated to orientate users to GUI

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-3/tp#181]
![image.png](https://raw.githubusercontent.com/Darren159/ped/main/files/5c3e96ce-20ac-4d79-be00-e6bb8677b533.png)

The UI screenshot in the quick start does not explain the components of the GUI which might confuse users.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Darren159/ped#9

**Comment by kanna-1** [comment]
Just need to add annotation, no need explain components (done in glossary already)
