### ISSUE TITLE
[PE-D][Tester A] Archiving Data Files feature is empty

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T14-3/tp#187]
![image.png](https://raw.githubusercontent.com/Darren159/ped/main/files/5cb78047-1d04-48bf-9ae3-0e03c5f8087d.png)

Upcoming feature is empty, can include something for users to look forward to.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Darren159/ped#15

**Comment by kanna-1** [comment]
Add a short description in the UG
