### ISSUE TITLE
[PE-D][Tester B] Does not allow certain very important attributes to be edited

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-3/tp#190]
There can be typos in extremely important attributes like name and IC, however these typos may or may not be spotted until quite later on, when the database has become massive, and has undergone a lot of changes. These important fields have to be allowed to be edited as the typos may or may not be spotted till much later. If there are concerns on duplicates in the data, perhaps there should be checking of duplicates in the parser stage instead of making these essential attributes unmodifiable.
![Screenshot 2023-11-03 at 10.27.41 PM.png](https://raw.githubusercontent.com/RiyaMehta2211/ped/main/files/3e7d9542-1fdd-463a-a385-ddc45db0c520.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: RiyaMehta2211/ped#2

**Comment by kanna-1** [comment]
In order to address this issue, we shall update our UG accordingly to inform users to be aware names and Nric are *NOT* editable.
