### ISSUE TITLE
Edge Case: Wrong Command Result for Logging empty list

### ISSUE THREAD

**Issue by WeeeHung** [AY2324S1-CS2103T-T14-3/tp#221]
While testing the Profile (for patients with appointment today) Listed on Logger Tab on App-start, I realised `log` does not show the right command result `Cannot log an empty list.` as  no `find` commands were done prior.

1. SS when `log` is performed on app-start (**With** Patients having appointment today)
[ Expects:  `Cannot log an empty list.` ] 
[ Actual: `The last filtered values have overridden the logger tab`] (side note: should this also be changed to overwritten)

![image](https://github.com/AY2324S1-CS2103T-T14-3/tp/assets/96626287/0702ad39-775d-4750-9b0f-f44889f45020)

3. SS when `log` is performed on app-start (**Without** Patients having appointment today)

![image](https://github.com/AY2324S1-CS2103T-T14-3/tp/assets/96626287/c48dc169-ae07-4efe-9e47-1efdb4a42f04)

**Comment by WZWren** [comment]
Ah, this is a simple fix - I didn't purge the `Predicate` used by `foundPersonList` when initializing the `ModelManager`.
```
    public ModelManager(ReadOnlyAddressBook addressBook, ReadOnlyUserPrefs userPrefs) {
        ...
        filteredPersons = new FilteredList<>(this.addressBook.getPersonList());
        foundPersonsList = new FilteredList<>(this.addressBook.getPersonList());
        foundPersonsList.setPredicate(PREDICATE_TODAY);                                // OFFENDING LINE

        this.logBook.setPersons(foundPersonsList);
        loggedFilteredPersons = new FilteredList<>(this.logBook.getPersonList());
    }
```
I
