### ISSUE TITLE
Logger: Bug involving Modified Duplicates

### ISSUE THREAD

**Issue by kanna-1** [AY2324S1-CS2103T-T14-3/tp#233]
This was a bug from PE-D that was resolved:
#166 by updating the UG to mention that the logger works as a snapshot so editing the patient should not edit the log.

However, there is a potential bug that is partially related to it.

Assume we have a patient John A.

Steps to reproduce:
1. Do a `find/A` and `log`.
2. We do a valid edit command on John A i.e. `edit n/John A <fields>`
3. We then do `alog` with the new John A after doing a `find/A`. 
4. An error: `Person(s) already in list is outputted.`

From the UG I am aware that this was mentioned:
> Duplicate patients will not be appended to the log.

But then I am not really sure if this is a bug. Should there be an updating of the log happening instead?

**Comment by WZWren** [comment]
After a meeting, we have determined this to be a bug. This is directly derived from our UG: 

>The logger tab does not update when logged patients' profiles are edited or deleted. The logger tab is intended to be a snapshot of the patients' details at the time that they were logged. To reflect the edited changes in the logger tab after a change has been made, do log after the change.

`alog` should update the edited person, as it is a snapshot at the point where `log` is called.

**Comment by kanna-1** [comment]
I tried solving this and reached this.

        for (Person person : model.getFoundPersonsList()) {
            if (model.getLogBook().hasPerson(person)) {
                Optional<Person> personOptional =
                        CommandUtil.findPersonByIdentifier(person.getName(), person.getId(), model.getLoggedFilteredPersonList());
                if (personOptional.isPresent() && personOptional.get().equals(person)) {
                    hasDupes = true;
                    duplicateClause += "\n  " + person.getName() + ", ID: " + person.getId();
                    continue;
                } else {
                    Person existingPerson = personOptional.orElse(person);
                    model.getLogBook().setPerson(existingPerson, person);
                }
            }
            model.getLogBook().addPerson(pers

**Comment by kanna-1** [comment]
This was my attempt to fix this bug:

        boolean hasDupes = false;
        String duplicateClause = "";
        for (Person person : model.getFoundPersonsList()) {
            if (model.getLogBook().hasPerson(person)) {
                Optional<Person> personOptional =
                        CommandUtil.findPersonByIdentifier(person.getName(), person.getId(), model.getLoggedFilteredPersonList());
                if (personOptional.isPresent() && personOptional.get().equals(person)) {
                    hasDupes = true;
                    duplicateClause += "\n  " + person.getName() + ", ID: " + person.getId();
                    continue;
                } else {
                    Person existingPerson = personOptional.orElse(person);
                    model.getLogBook().setPerson(existingPerson, person);
                }
            }
            model.getLogBook().addPerson(person);
        }

        return hasDupes
                ? new CommandResult(String.format(MESSAGE_DUPLICATES, duplicateClause))
                : new CommandResult(MESSAGE_SUCCESS);
    }
    
The idea is to check if the logbook contains the person in the foundList, we find that person using the findPersonByIdentifier and compare using equals with the person in the foundList. The code works. 
   
**But for some reason there is no output message produced.**

**Comment by kanna-1** [comment]
Before running alog command (I just do a find first):
![Screenshot (293)](https://github.com/AY2324S1-CS2103T-T14-3/tp/assets/106588483/71d47e58-4c1d-4203-97eb-7f7be85c000b)

After running alog command
![Screenshot (294)](https://github.com/AY2324S1-CS2103T-T14-3/tp/assets/106588483/cd2bd421-e580-4c7b-a0b3-35d7b76037b5)
**Notice** how the logger tab has changed but there is no output message.
