### ISSUE TITLE
Implement New field in Person Class 

### ISSUE THREAD

**Issue by WeeeHung** [AY2324S1-CS2103T-T14-3/tp#26]
To successfully implement the changes, we need to add new fields to the Person class.

In particular, we need the following fields:
 * IC (1)
 * ~~Ward (0...1)~~
 * Medical History (0...*)
 * Close Contacts (0...1)
 * Appointment Time (0...1)

For Medical History, it is possible to convert Tags for a patient.

**Comment by WZWren** [comment]
We have since limited the scope of the app to target smaller medical practices such as clinics, over large hospitals. Therefore, the Ward feature would be redundant. While the UG has not been modified yet, we will modify it to reflect the new plan.
