### ISSUE TITLE
New Fields: Add logic to verify field validity.

### ISSUE THREAD

**Issue by WZWren** [AY2324S1-CS2103T-T14-3/tp#67]
#26: We are currently using dummy values for the new fields, to let concurrent development of the MVP functions be done. However, fields like NRIC should have some verification integrated within them.

This is likely most relevant to the Add command, with some ties to Edit.

**Comment by kanna-1** [comment]
Validation for appointment has been implemented. New fields are no longer using dummy values.

**Comment by kanna-1** [comment]
Due to uncertainties regarding the validation of NRIC number and the vagueness on the actual algorithm for valid NRIC checks, will the validation of NRIC in view.

**Comment by WZWren** [comment]
While validation of NRIC is important, we recognize that users may want to use their own definition of an Identification field, like a shorthanded NRIC approach, etc. Therefore, we will leave NRIC as a field that can take in any value.
